name: Build and Deploy Frontend to EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular apps
        run: npm run build:all

      - name: Compress dist folder
        run: tar -czf build.tar.gz -C dist .

      - name: Copy to EC2 using SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "build.tar.gz"
          target: "/home/ec2-user/"

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            mkdir -p /var/www/html/mybank
            cd /tmp
            aws s3 cp s3://mybank-deploy/build.tar.gz build.tar.gz
            sudo rm -rf /var/www/html/mybank/*
            sudo tar -xzf build.tar.gz -C /var/www/html/mybank
            sudo systemctl restart nginx
