name: Build and Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular apps
        run: npm run build:all

      - name: Compress build folder
        run: tar -czf build.tar.gz -C dist mfe-sucesso  # <-- substitua por sua pasta final correta

      - name: Upload build to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: build.tar.gz
          target: "/home/ubuntu/"

      - name: SSH and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo mkdir -p /var/www/html/mybank
            sudo rm -rf /var/www/html/mybank/*
            tar -xzf /home/ubuntu/build.tar.gz -C /var/www/html/mybank
            sudo systemctl restart nginx
